pipeline {
    agent any 

    parameters {
            string(defaultValue: "Test", description: "what depolyment is this?", name: "deployEnv")
    }
    stages {
        stage ("Demo"){
            steps {
                    echo "string is set to: ${params.deployEnv}"   
            }
        }
            stage ("Demo-timileyinao"){
            steps {
                    echo "string is set to: Job successful"   
            } 
                     
        }
    }
}
