apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: ngnix
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
  tolerations:
    - key: "team"
      operator: "Equal"
      value: "devops"
      effect: "NoSchedule"