#! /bin/bash -e
#
# Test Docker image

cd $(dirname $0)/..

# Test that the modified Java truststore is in the final image
echo
echo "***** Press Enter at the password prompt *****"
docker run -it --rm java-multistage:latest keytool -list --cacerts -alias debian:ca.pem
echo
echo "***** It must match this fingerprint for the alias \"debian:ca.pem\" *****"
echo "Certificate fingerprint (SHA-256): 0C:25:8A:12:A5:67:4A:EF:25:F2:8B:A7:DC:FA:EC:EE:A3:48:E5:41:E6:F5:CC:4E:E6:3B:71:B3:61:60:6A:C3"
echo